services:
  app:
    build: .
    container_name: store-app
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - internal
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:latest
    container_name: store-mysql-db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=store-db
    volumes:
      - /Users/t0351dn/db_volumes/store-db:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - internal

networks:
  internal: