spring:
  application:
    name: store
  datasource:
    url: jdbc:mysql://localhost:3306/store-db?createDatabaseIfNotExist=true
    username: root
    password: password
  jpa:
    show-sql: true
  jwt:
    secret: ${SPRING_JWT_SECRET}
    accessTokenExpiration: 300
    refreshTokenExpiration: 604800