spring:
  application:
    name: store
  jwt:
    secret: ${SPRING_JWT_SECRET}
    accessTokenExpiration: 7200 # 2h
    refreshTokenExpiration: 604800 # 7d
  profiles:
    active: dev

stripe:
  secret-key: ${STRIPE_SECRET_KEY}
  webhook-secret-key: ${STRIPE_WEBHOOK_SECRET_KEY}