spring:
  application:
    name: store
  datasource:
    url: jdbc:mysql://localhost:3306/store-db?createDatabaseIfNotExist=true
    username: root
    password: password
  jpa:
    show-sql: true
  jwt:
    secret: ${SPRING_JWT_SECRET}
    accessTokenExpiration: 7200 # 2h
    refreshTokenExpiration: 604800 # 7d

stripe:
  secret-key: ${STRIPE_SECRET_KEY}
  webhook-secret-key: ${STRIPE_WEBHOOK_SECRET_KEY}

websiteUrl: http://localhost:3000